name: Java CI with Maven

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
      branch:
        type: string
        required: true
      pom-file:
        type: string
        required: false


        
jobs:
  build:
    env:
      java-home: secrets.JAVA_HOME
      maven-home: secrets.MAVEN_HOME
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
    - name: Set parameters
      id: parameters
      run: |
        "${{ env.java-home }}" >> $env:GITHUB_PATH
        "${{ env.maven-home }}" >> $env:GITHUB_PATH
        
        if ("${{ inputs.pom-file }}" -eq "") {
          "pom-file=pom.xml" >> $env:GITHUB_OUTPUT
        } else {
          "pom-file=${{ inputs.pom-file }}" >> $env:GITHUB_OUTPUT
        }
      
    - name: Build with Maven
      run: mvn -B package --file ${{ steps.parameters.outputs.pom-file }}
      
    - name: Clean
      if: always()
      run: mvn -B clean --file ${{ steps.parameters.outputs.pom-file }}
